### PR TITLE
Fixes #6 Add an example that uses eth price feed from uniswap via TheGraph

### LINKED ISSUE #6: Publish asset: eth/usdt on TheGraph, into Polygon
- [ ] Publish asset: eth/usdt on TheGraph (graphql), into Polygon. 
- [ ] Update eth-predict2.md to also load it  

Parent epic: [predict-eth#3](https://github.com/oceanprotocol/predict-eth/issues/3)

### PR DESCRIPTION
**Pull request by jfdelgad**
Fixes #6  .

Changes proposed in this PR:

-  Add example using data from theGraph (GraphQL) for prediction
- 
-

### CODE REVIEW

**Comment by trentmc** [comment]
This PR has large DRY violations. If you don't know DRY yet, check out: https://www.plutora.com/blog/understanding-the-dry-dont-repeat-yourself-principle. Specifically, predict-eth-graphQL-data-linear-models.md appears identical to predict-eth-ocean-data-linear-models.md, save for one line - the `did` value.

The github issue included: "Update eth-predict2.md to also load it [new data]". The "also" was to show how to merge >1 datasets to be used together to build a predictive model. But since it's basically the same data, and therefore not helpful, let's  defer work on merging >1 datasets to "in eth-predict2.md, improve model-based prediction".

What to do here? There are three other READMEs that show how to get ETH/USDT data from three different sources: get-data-ccxt-binance.md, get-data-ocean-binance.md, get-data-binance-direct.md. 

I recommend to make a similar README here: how to ETH/USDT data from this fourth source, TheGraph.

**Comment by jfdelgad** [comment]
> This PR has large DRY violations. If you don't know DRY yet, check out: https://www.plutora.com/blog/understanding-the-dry-dont-repeat-yourself-principle. Specifically, predict-eth-graphQL-data-linear-models.md appears identical to predict-eth-ocean-data-linear-models.md, save for one line - the `did` value. Copying large swaths of code will make it all hard to maintain.
> 
> The github issue included: "Update eth-predict2.md to also load it [new data]". The "also" was to show how to merge >1 datasets to be used together to build a predictive model. But since it's basically the same data, and therefore not helpful, let's defer work on merging >1 datasets to "in eth-predict2.md, improve model-based prediction".
> 
> What to do here? There are three other READMEs that show how to get ETH/USDT data from three different sources: get-data-ccxt-binance.md, get-data-ocean-binance.md, get-data-binance-direct.md.
> 
> I recommend to make a similar README here: how to ETH/USDT data from this fourth source, TheGraph.


@trentmc I agree that the code (and perhaps the example) is redundant. There is no difference between downloading a csv file and an asset based on graphQL. My suggestions are:

- Remove this task. Even as an example, how to get a graphQL dataset is not so useful, because this will be the same as any other ocean asset download, for instance: get-data-ocean-binance.md
- The task #8 should be aimed to combine features, not necessarily assets. For instance the ocean dataset with binance info, contains volume and timestamp among other features. These can be combined with the eth value to make (possibly) better predictions.

**Comment by trentmc** [comment]
> Remove this task. Even as an example, how to get a graphQL dataset is not so useful, because this will be the same as any other ocean asset download, for instance: get-data-ocean-binance.md

Yes, it's the same as other assets. But ask yourself: why do we already have three different ways to download the asset? 

That's a rhetorical question of course:) The answer is: to show the user how to get data from various types of locations: direct API, ccxt, Ocean. Because each location has its own characteristics: other data that may be available, and different latency / convenience / flexibility tradeoffs. 

This is another type of location yet (TheGraph). Therefore I recommend to add getting this asset, side by side with the other three ways.

> The task [Jaime] improve model-based prediction #8 should be aimed to combine features, not necessarily assets. 

You can combine raw data or features however you like, all in the name of reducing prediction error.

**Review by AnaLoznianu — APPROVED** [review]

**Comment by trentmc** [comment]
> AnaLoznianu approved these changes 4 minutes ago

@AnaLoznianu fyi there are large DRY violations

@jfdelgad please do not merge as-is, it would be extremely hard to maintain this

**Comment by jfdelgad** [comment]
> > AnaLoznianu approved these changes 4 minutes ago
> 
> @AnaLoznianu fyi there are large DRY violations
> 
> @jfdelgad please do not merge as-is, it would be extremely hard to maintain this

@trentmc 
Please take a look at the changes:

I added a new example of getting data from the deployed asset (graphQL) 
I removed the previous readme with the prediction as it is redundant

Let me know

**Review by juanpablovs — APPROVED** [review]
You all raise very valid concerns. Although I do think that there is value in showing that data obtained from several sources can be processed in similar and different ways.
Btw, in line 28 there was another typo (sued)

**Review by trentmc — APPROVED** [review]

**Pull request merged**
