### PR TITLE
Create ongoing challenge-df.md

### LINKED ISSUE #138: Prepare new challengeDF.md
### DoD:
- [ ] Create new challengeDF.md readme that will remain fixed

### PR DESCRIPTION
**Pull request by idiom-bytes**
Fixes #138 

Changes proposed in this PR:
- [x] challenge-df.md file has all required updates
- [x] md file can can be linked from df-challenges

### CODE REVIEW

**Comment by idiom-bytes** [comment]
## Automating Key Dates
I can see they are in the first wed->thurs of the month.
- We need to update this file once a month.
- We have to write this code for the website to report these numbers.
- The website right now uses a static config file to figure out [numbers/dates/etc...](https://github.com/oceanprotocol/df-web/blob/main/src/utils/metadata/epochs/epochs.json)

```
### 0.2 Key dates
- Submission deadline: Wed Jul 5, 2023 at 23:59 UTC.
- Prediction at times: Thu Jul 6, 2023 at 00:05 UTC, 00:10, ..., 1:00 (12 predictions total).
```

Is there a desire to update this? Candidate solutions:
- [ ] Move more of the dynamic data outisde this file and have the .MD point to the websites.
- [ ]  Have a cron job overwrite these lines/recreate the file.

**Comment by KatunaNorbert** [comment]
Or we can have one of the following:
- remove the section and relay on df page dates
- keep section but use more generic dates and refer to df webpage

**Comment by KatunaNorbert** [comment]
I see we are both proposing the same solution of removing dates and point to df-web so let's do that

**Comment by KatunaNorbert** [comment]
Pushed following update:
- updated prizes section: changed rewards currency from $ to OCEAN, updated description to say rewards are going to be allocated instead of directly distributed to winner.
- updated key dates to have a more generic date so we don't have to update each week
- added new claim rewards section
- updated introduction section to give more information about DF and Challenge relation
- added links to df-web

**Comment by idiom-bytes** [comment]
Great updates! Looks good!

**Pull request merged**
